-- PREPARANDO TABELA PARA EXEMPLO

CREATE TABLE #TMP_TESTE_CONTRATO
(
 CONTRATO	VARCHAR(20)
,ORDEM		VARCHAR(2)
)

INSERT INTO #TMP_TESTE_CONTRATO VALUES ('001', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('002', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('003', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('004', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('005', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('006', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('007', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('008', NULL)
INSERT INTO #TMP_TESTE_CONTRATO VALUES ('009', NULL)

-- SELECT PARA DEMONSTRACAO ANTES DO CURSOR
SELECT *, 'ANTES DO CURSOR' AS VERIFICACAO FROM #TMP_TESTE_CONTRATO ORDER BY CONTRATO

-- DECLARAÇÃO DE VARIAVEIS UTILIZADAS NO CURSOR
DECLARE @CONTRATO VARCHAR(100)
DECLARE @CONT INT

-- SETANDO VARIAVEL UTILIZADA NO UPDATE
SET @CONT = 1

-- CURSOR PARA PERCORRER OS REGISTROS
DECLARE CURSOR_CONTRATO CURSOR FOR
SELECT DISTINCT CONTRATO FROM #TMP_TESTE_CONTRATO ORDER BY CONTRATO

-- ABRINDO CURSOR
OPEN CURSOR_CONTRATO

-- LENDO A PRÓXIMA LINHA
FETCH NEXT FROM CURSOR_CONTRATO INTO @CONTRATO

-- PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
WHILE @@FETCH_STATUS = 0
BEGIN

-- EXECUTANDO AS ROTINAS DESEJADAS MANIPULANDO O REGISTRO
	
	UPDATE CON SET ORDEM = @CONT 
	FROM #TMP_TESTE_CONTRATO CON
	WHERE CONTRATO = @CONTRATO

	SET @CONT = @CONT + 1

-- LENDO A PRÓXIMA LINHA
FETCH NEXT FROM CURSOR_CONTRATO INTO @CONTRATO
END

-- FECHANDO CURSOR PARA LEITURA
CLOSE CURSOR_CONTRATO

-- FINALIZADO O CURSOR
DEALLOCATE CURSOR_CONTRATO

-- SELECT PARA DEMONSTRACAO DEPOIS DO CURSOR
SELECT *, 'DEPOIS DO CURSOR' AS VERIFICACAO FROM #TMP_TESTE_CONTRATO ORDER BY CONTRATO